project: QU4-CNN
device: cuda:0
net: model.CNN
optimizer: torch.optim.adamw.AdamW
scheduler: hyperbolic_lr.ExpHyperbolicLR
epochs: 20
batch_size: 128
seeds: [89, 231, 928]
net_config:
  num_conv_layers: 3
  num_fc_layers: 2
  conv_channels: 8
  fc_nodes: 128
optimizer_config:
  lr: 1.e-3 # Must contain dot for float
scheduler_config:
  upper_bound: 250
  max_iter: 50
  infimum_lr: 1.e-5
early_stopping_config:
  enabled: false
  patience: 10
  mode: min # 'min' or 'max'
  min_delta: 0.0001 # Percent
